development:
  adapter: mysql2
  encoding: utf8
  database: the_good_pizza
  username: root
  host: 127.0.0.1
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false
